packageExtensions:
  '@atls-ui-parts/layout@*':
    dependencies:
      '@emotion/css': 11.11.0
      csstype: 3.1.2
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': 11.11.0
  'swiper@*':
    peerDependencies:
      'react': "*"
yarnPath: .yarn/releases/yarn-remote.cjs
